##############################################################################
#  Copyright Christopher Kormanyos 2021.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: pi-crunch-metal
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-arm:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        suite: [ bcm2835_raspi_b ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install gcc-arm-none-eabi
      - name: target-arm-${{ matrix.suite }}
        run: |
          ./target/build/build.sh ${{ matrix.suite }} rebuild
          ls -la ./bin/pi-crunch-metal.hex ./bin/pi-crunch-metal.s19 ./bin/kernel.img
        working-directory: ./
  msvc-msbuild:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        suite: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: msvc-msbuild-${{ matrix.suite }}
        env:
          PATH: '${env:PATH};C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64'
        run: |
          MSBuild -m pi-crunch-metal.sln -p:Configuration=${{ matrix.suite }} -p:Platform=x64 /t:Rebuild
          dir .\tmp\${{ matrix.suite }}\ref_app.exe
        working-directory: ./
